name = "Cobblemon plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72a5dd30b86cf1f6e09408e9b0849231ea55f04b2ab7b76f531f5a867baa55d6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
