name = "Cobblemon plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bd3a4c4cf9abd61640a69f3d8b62bd42fddcf28e65d605778636d53fa958290"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
