name = "Cobblemon plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ae0c3ffc7181403c746b6949f4c74fba34503d2ec66c51f50c514b335b0f416"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
